type Project @model @auth(rules: [
  {allow: public, provider: identityPool, operations: [read]}
  {allow: groups, groups: ["Admins"], operations: [read, create, update, delete]},
]) {
  id: ID!
  name: String! @index(name: "byName", queryField: "ProjectByName")
  slug: String! @index(name: "bySlug", queryField: "ProjectBySlug")
  images: AWSJSON
  thumbnail: String
  video: String
  top4: Boolean!
  href: String
  github: String
  role: String
  context: String
  steps: AWSJSON
  description: String
  years: Int
  skills: [Skill] @hasMany
  category: Category @hasOne
}

type Skill @model @auth(rules: [
  {allow: public, provider: identityPool, operations: [read]}
  {allow: groups, groups: ["Admins"], operations: [read, create, update, delete]},
]) {
  id: ID!
  name: String! @index(name: "byName", queryField: "SkillByname")
  logo: String
  colisionLogo: String
  typeID: String!
  type: SkillType @hasOne
}

type SkillType @model @auth(rules: [
  {allow: public, provider: identityPool, operations: [read]}
  {allow: groups, groups: ["Admins"], operations: [read, create, update, delete]},
]) {
  id: ID!
  name: String!
}

type Category @model @auth(rules: [
  {allow: public, provider: identityPool, operations: [read]}
  {allow: groups, groups: ["Admins"], operations: [read, create, update, delete]},
]) {
  id: ID!
  name: String! @index(name: "byName", queryField: "CategoryByname")
  slug: String! @index(name: "bySlug", queryField: "CategoryBySlug")
  project: [Project] @hasMany
}

type Gallery @model @auth(rules: [
  {allow: public, provider: identityPool, operations: [read]}
  {allow: groups, groups: ["Admins"], operations: [read, create, update, delete]},
]) {
  id: ID!
  place: String
  date: AWSDate
  picture: String
}
